### ISSUE TITLE
用此工具写出来的论文“重复率”是不是会很高？

### ISSUE THREAD

**Issue by linux0ne** [tianlian0/aided_writing#1]
我看了你demo，按照这个节奏写下去，论文是很方便的写出来了，知道每一个观点的话该怎么写下去了，但是这样写好的论文去查重的时候，那不得和整个大数据论文库里的内容重复得很高么？  换句话说，都是别人说过的话，现成的拿过来了。

我不知道我有没有理解错。

难道说每个备选的词条或语句都是经你的程序“降重”后的？  如果是，那就牛BBBB了。

**Comment by tianlian0** [comment]
“辅助写作”工具，标题写的已经很明白，重在“辅助”。你说的不叫“辅助写作”叫“自动生成”。用这个工具自动生成文章重复率自然会很高。重在“辅助”，要是机器能自动生成一篇完全完美的论文以后还用的着人来写吗？本科和研究生写论文还有意义吗？
